//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string CLASS { get; set; }
        public decimal EMAIL { get; set; }
        public decimal PHONENO { get; set; }
    }
}
